FROM gradle:6.4.1-jdk14
RUN echo `whoami`
RUN echo "Stage 1"
RUN ls -la /home/gradle/.gradle
USER gradle
RUN mkdir /home/gradle/project
WORKDIR /home/gradle/project
COPY --chown=gradle:gradle build.gradle settings.gradle ./
RUN echo "Stage 2"
RUN ls -la /home/gradle/.gradle
RUN gradle -i clean build
RUN echo "Stage 3"
RUN ls -la /home/gradle/.gradle
COPY src ./src
RUN gradle -i bootJar